#!/bin/bash

#font colors vars
cyan=$(tput setaf 6)
reset=$(tput sgr0)

echo "Enumerating host ..."
echo "$cyan####################################################"
echo "##################### SYSTEM #######################"
echo "####################################################$reset"
echo "System: $(whoami)@$(hostname)"
echo "OS: $(rpm -qia '*release*') | $(uname -a)"
echo "Date/Time: $(date)"
echo "Up Time: $(uptime)"
echo "Logged In: $(who)"
echo "Accounts: $(ls /home/)"
echo "$cyan####################################################"
echo "#################### Resources #####################"
echo "####################################################$reset"
echo "$(top -b -n1)"
echo "$cyan####################################################$reset"
echo "$(free)"
echo "$cyan####################################################"
echo "#################### SERVICES ######################"
echo "####################################################$reset"
echo "$(service puppet status)"
echo "$cyan####################################################"
echo "################### NETWORKING #####################"
echo "####################################################$reset"
echo "$(ifconfig eth0)"#em1 for workstations, eth0 for test machine
echo "$cyan####################################################"
echo "##################### TCPDUMP ######################"
echo "####################################################$reset"
echo "$(tcpdump -i em1)"
echo "$cyan####################################################"
echo "##################### DEVICES ######################"
echo "####################################################$reset"
echo "$(lsusb)"
echo "$cyan####################################################$reset"
echo "$(lsblk)"
echo "$cyan####################################################$reset"
echo "$(lspci)"
echo "$cyan####################################################"
echo "##################### STORAGE ######################"
echo "####################################################$reset"
echo "$(df -h)"
echo "$cyan####################################################$reset"
echo "$(fdisk -l)"
echo "$cyan####################################################"
echo "################### OPEN FILES #####################"
echo "####################################################$reset"
echo "$(lsof)"
echo "$cyan####################################################"
echo "################# Last Modified ####################"
echo "####################################################$reset"
echo "$(find $1 -type f -print0 | xargs -0 stat --format '%Y :%y %n' | sort -nr | cut -d: -f2- | head)"
echo "$cyan####################################################"
echo "############ Reboot/Shutdown History ###############"
echo "####################################################$reset"
#This will be changed later. Reboots and shutdowns will be merged into a single list
#to provide better information for troubleshooting issues. 
#Dates can be converted to epoch via date "+%s" -d "02/20/2013 08:41:15"
#The merge and sort the lists and convert the dates back to readable format.
#Dates can be converted back from epoch with date -d @1234567890
echo "$(last reboot | less)"
echo "$cyan####################################################$reset"
echo "$(last -x | grep shutdown | less)"
echo "$cyan####################################################"
echo "####################################################"
echo "####################################################$reset"
echo "Enumeration complete ..."

